### ISSUE TITLE
Edge cases not covered in `ASN1wrap` and `stripspace`

### ISSUE THREAD

**Issue by doorholez** [nimpo/hash-bash-ssl#2]
in function `ASN1wrap`, the result of length larger than 127 is not correct. The first byte of length should +128 to make the 8th bit to 1. And it seems to print `lh` twice.
in function `stripspace`, the situation of length larger than 127 (more than only 1 length byte) in removing the leading spaces is not covered.
since i'm not good at bash, i will try to correct it slowly. Maybe you can correct it before i pull request :)

**Comment by nimpo** [comment]
Merged pull request from @doorholez
